routes = [
  { pattern = "diurivj.com", custom_domain = true },
  { pattern = "www.diurivj.com", custom_domain = true }
]

workers_dev = true
name = "diurivj"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-12-30"
main = "./build/server/index.js"

[assets]
directory = "./build/client/"
binding = "ASSETS"
experimental_serve_directly = false

[observability]
enabled = true
